spring:
  #Redis相关配置
  redis:
    database: 5
    # 配置Redis的主机地址，需要修改成自己的
    host: 119.23.25.226
    port: 6379
    timeout: 5000
    lettuce:
      pool:
        # 连接池中的最大空闲连接，默认值也是8。
        max-idle: 500
        # 连接池中的最小空闲连接，默认值也是0。
        min-idle: 50
        # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)
        max-active: 1000
        # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
        max-wait: 2000
  datasource:
    name: springboot
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filter: stat
      #mysql驱动
      driver-class-name: com.mysql.cj.jdbc.Driver
      #基本属性
      url: jdbc:mysql://119.23.25.226:3306/book?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: root@mylzl

tengxun:
  appid: 1400222097
  appkey: fad3628ae9997cbf610de8f1b19894da



pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql